name: nxtgm
channels:
  - conda-forge

dependencies:
  # Build tools
  - cmake
  - doctest
  - cxx-compiler
  - ninja
  # dependencies
  - boost-cpp
  - fmt
  - nlohmann_json
  - highs
  - xtensor
  - xplugin >= 0.2.0
  # dependencies pythonbindings
  - python
  - pybind11
  - xtensor-python
  - numpy
  - pytest
  # for examples
  - sphinx-gallery
  - matplotlib
  - scikit-image
  # documentation
  - doxygen
  - sphinx
  - sphinx_rtd_theme
  - breathe
  - sphinx-sitemap
