#pragma once
#ifndef NXTGM_VERSION_HPP
#define NXTGM_VERSION_HPP

#define NXTGM_VERSION_MAJOR 0
#define NXTGM_VERSION_MINOR 1
#define NXTGM_VERSION_PATCH 0
#define NXTGM_VERSION "0.1.0"

#endif // NXTGM_VERSION_HPP
