name: Build with conda
on:
    push:
    pull_request:

jobs:
  unix:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:


      - uses: actions/checkout@v3

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Install Conda environment from environment.yml
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'


      - name: cmake configure
        shell: bash -l {0}
        run: |
          mkdir -p bld
          cd bld
          cmake \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_TESTS=ON \
              -DBUILD_PYTHON=ON \
              -DBUILD_DOCS=ON \
          .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX

      - name: Build
        shell: bash -l {0}
        run: |
          cd bld
          make -j ${{ steps.cpu-cores.outputs.count }}

      - name: Run C++ tests
        shell: bash -l {0}
        run: |
            cd bld
            ctest --output-on-failure

      - name: Run Python tests
        shell: bash -l {0}
        run: |
            cd bld
            make python_tests

      - name: install
        shell: bash -l {0}
        run: |
            cd bld
            make install

      - name: Build docs
        shell: bash -l {0}
        run: |
            cd bld
            make docs


  windows:
    strategy:
      matrix:
        include:
          - os: windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3

      - name: Install Conda environment from environment.yml
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            cmd.exe
          cache-environment: true
          post-cleanup: 'all'

      - name: build and test
        shell: cmd /C CALL {0}
        run: |
          mkdir bld
          cd bld
          cmake .. ^
            -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DBUILD_TESTS=ON ^
            -DBUILD_PYTHON=ON ^
            -DBUILD_DOCS=OFF ^
            -DCMAKE_PREFIX_PATH="%CONDA_PREFIX%\Library" ^
            -DCMAKE_INSTALL_PREFIX="%CONDA_PREFIX%
          cmake --build . --config Release
          cmake --install . --config Release

      - name: run tests
        shell: cmd /C CALL {0}
        run: |
          cd bld
          tree /f /a
          ctest --output-on-failure --config Release
