name: emscripten-build
on:
    push:
    pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          emsdk_ver: ["3.1.45"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1
        with:
            environment-name: nxtgm
            create-args: >-
                microsoft::playwright
                python
                nodejs
            init-shell: bash

      ################################################################
      # setup emsdk
      ################################################################
      - name: "setup emsdk"
        shell: bash -el {0}
        run: |
            ./emsdk/setup_emsdk.sh   ${{ matrix.emsdk_ver }} ~/emsdk_install




      - name: Build via npm
        shell: bash -el {0}
        run: |
            npm run build_wasm
            npm run prepare
            npm run build
